[package]
name = "flasher"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Wilding <mbwilding@gmail.com>"]

[dependencies]
anyhow = "1.0"
api = { path = "../../libraries/api" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
